### ISSUE TITLE
Index - Automatic Timestep

### ISSUE THREAD

**Issue by Steiner0815** [GlyphXTools/particle-editor#11]
Hi Mike, 
Another Wish from my Side :) 
It would be nice to have a automatism to set the timesteps in the Index Window. 

A example: When I want to use a Particletexture for a animation with 64 Frames I have to set all 64 timesteps manualy. 
When the Editor could set the Timesteps from 0 to 63 and from 0 to 100 in the Timelapse, it would be much more faster and also easier to set, because without a Zoom Function in the Graph Window its hard to set them all correctly.

**Comment by MikeLankamp** [comment]
@Steiner0815, have you tried setting the interpolation to "linear" instead of "step"? The game doesn't *require* the interpolation to be "step"; it simply truncates the interpolated value to an integer, so if you do a linear interpolation from start to finish that should be the same result as equally-spaced step-interpolations along the way.

**Comment by Steiner0815** [comment]
@MikeLankamp Well, no... haha thanks! I just used existing Particle Effects as a basis... and there was step... Thx for reply mike!

**Comment by MikeLankamp** [comment]
No problem! Glad it works for you. Closing issue.
